name: gradle-ci

on: [ push ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt'
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/loom-cache
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Grant execute permission to gradlew
      run: chmod +x gradlew
    - name: Build artifacts
      run: ./gradlew build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: entityrange-artifact
        path: build/libs/*[0-9].jar
